# Jekyll Configuration for GitHub Pages
title: "Duy's Personal Blog"
description: "Keeping track of my learning journey."
baseurl: ""
url: "https://luongduy.github.io"

# Author information
author:
  name: "Duy Luong"
  email: "duy.luonganh@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Language and timezone
lang: en
timezone: Asia/Tokyo

# Social links (optional)
social:
  - name: "GitHub"
    url: "https://github.com/luongduy"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/duy-luong-87168762/"

# SEO settings
seo:
  type: "Blog"
